name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: apps musicHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build & test backend (multi-module)
        run: mvn -B -f apps/pom.xml verify

      - name: Upload surefire reports (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: maven-test-reports
          path: '**/target/surefire-reports/*.xml'

      - name: Set up Node.js (for frontend unit tests)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend deps (npm)
        working-directory: apps/webui
        run: npm install

      - name: Run frontend unit tests (Vitest)
        working-directory: apps/webui
        run: npx vitest run