name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install root dependencies
        run: pnpm install

      - name: Build frontend
        run: pnpm --filter frontend build

      - name: Test frontend
        run: pnpm --filter frontend test

      - name: Build and test backend
        run: mvn -B package --file apps/backend/pom.xml 